apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: -pipeline-run-init
  namespace: quarkus-app
  # annotations:
  #   argocd.argoproj.io/hook: PostSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: -pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/slallemand/quarkus-app.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/quarkus-app/
  pipelineRef:
    name: -pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
